export const variantStyles = {
  primary: "bg-primary-strong text-white hover:bg-primary cursor-pointer",
  secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/70 cursor-pointer",
  accent: "bg-accent text-accent-foreground hover:bg-accent/70 cursor-pointer",
  ghost: "bg-transparent text-foreground/70 hover:bg-muted hover:text-foreground border border-transparent focus:ring-0 cursor-pointer",
  ghostPrimary: "bg-transparent text-primary-strong hover:bg-primary-soft border border-transparent cursor-pointer",
  ghostSecondary: "bg-transparent text-secondary-foreground hover:bg-secondary border border-transparent cursor-pointer",
  ghostAccent: "bg-transparent text-accent-foreground hover:bg-accent border border-transparent cursor-pointer",
  ghostDanger: "bg-transparent text-destructive hover:bg-destructive/10 border border-transparent cursor-pointer",
  outline: "bg-transparent text-primary-strong border border-primary hover:bg-primary-soft focus:ring-0 cursor-pointer",
  outlineSecondary: "bg-transparent text-foreground/70 border border-border hover:bg-secondary hover:text-foreground focus:ring-0 cursor-pointer",
  outlineAccent: "bg-transparent text-foreground/70 border border-foreground/30 hover:bg-accent hover:text-foreground focus:ring-0 cursor-pointer",
  danger: "bg-destructive text-white hover:bg-destructive/85 cursor-pointer",
  dangerOutline: "bg-transparent text-destructive border border-destructive hover:bg-destructive hover:text-white focus:ring-0 cursor-pointer",
}
