export const variantStyles = {
  primary: "bg-gradient-primary text-white hover:bg-primary/80 cursor-pointer",
  secondary: "bg-gradient-secondary text-foreground/60 hover:bg-secondary/80 cursor-pointer",
  accent: "bg-gradeint-accent text-foreground/60 hover:bg-accent/80 cursor-pointer",
  ghost: "bg-transparent text-foreground/60 border border-transparent focus:ring-0 cursor-pointer",
  ghostPrimary: "bg-transparent text-primary border border-transparent cursor-pointer",
  ghostSecondary: "bg-transparent text-secondary border border-transparent cursor-pointer",
  ghostAccent: "bg-transparent text-accent border border-transparent cursor-pointer",
  ghostDanger: "bg-transparent text-destructive border border-transparent cursor-pointer",
  outline: "bg-transparent text-primary border border-primary hover:bg-primary hover:text-foreground focus:ring-0 cursor-pointer",
  outlineSecondary: "bg-transparent text-foreground/60 border border-border hover:bg-secondary hover:text-foreground focus:ring-0 cursor-pointer",
  outlineAccent: "bg-transparent text-foreground/60 border border-foreground/60 hover:bg-accent hover:text-foreground focus:ring-0 cursor-pointer",
  danger: "bg-destructive text-white hover:bg-destructive/80 cursor-pointer",
  dangerOutline: "bg-transparent text-destructive border border-destructive hover:bg-destructive hover:text-destructive focus:ring-0 cursor-pointer",
}